using System;
using System.Reflection;
using TSClientGen.Extensibility.ApiDescriptors;

namespace TSClientGen.Extensibility
{
	/// <summary>
	/// Extensibility point for tweaking descriptors for api methods and their parameters
	/// before they are processed by the TypeScript code generation
	/// </summary>
	public interface ICustomMethodDescriptorProvider
	{
		/// <summary>
		/// Takes a method descriptor generated by the api discovery
		/// and returns a modified descriptor to use for code generation.
		/// </summary>
		/// <remarks>
		/// Return null from this method if you want to exclude the api method from the code generation.
		/// </remarks>
		MethodDescriptor DescribeMethod(Type controllerType, MethodInfo methodInfo, MethodDescriptor method);
	}
}