using System;
using TSClientGen.Extensibility.ApiDescriptors;

namespace TSClientGen.Extensibility
{
	/// <summary>
	/// Extensibility point for providing custom mappings of .net types to TypeScript types.
	/// This is for altering complex interface definition such as altering the set of interface members.
	/// </summary>
	public interface ITypeDescriptorProvider
	{
		/// <summary>
		/// Takes an interface descriptor generated by the api discovery
		/// and returns a modified descriptor to use for code generation.
		/// </summary>
		TypeDescriptor DescribeType(Type modelType, TypeDescriptor descriptor);		
	}
}